# Generated by Django 5.0.2 on 2024-02-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='division name')),
                ('year', models.CharField(max_length=4, verbose_name='division year')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, max_length=25, verbose_name='Team slug')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Team name')),
                ('win', models.IntegerField(default=0, verbose_name=' Total winning')),
                ('lose', models.IntegerField(default=0, verbose_name='Total losing')),
                ('draw', models.IntegerField(default=0, verbose_name='Total drawing')),
                ('goals', models.IntegerField(default=0, verbose_name='Total team goals')),
                ('missed_goals', models.IntegerField(default=0, verbose_name='Total team missed goals')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Total team yellow cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Total team red cards')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_api.division', verbose_name='Team division')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GK', 'Goalkeeper'), ('PL', 'Player'), ('CH', 'COACH')], max_length=30, verbose_name='role on field')),
                ('f_name', models.CharField(max_length=30, verbose_name='First name')),
                ('s_name', models.CharField(max_length=30, verbose_name='Second name')),
                ('year_born', models.IntegerField(blank=True, null=True, verbose_name='Year born')),
                ('image', models.ImageField(upload_to='static/player/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>/photo/')),
                ('goals', models.IntegerField(default=0, verbose_name='Total player goals')),
                ('assists', models.IntegerField(default=0, verbose_name='Total player assists')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Total player yellow cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Total player red cards')),
                ('team', models.ForeignKey(default='Without teams', on_delete=django.db.models.deletion.PROTECT, to='general_api.team', verbose_name='Team')),
            ],
        ),
    ]
